@startuml

class Country {
    + Country(name : String, population : long, area : double)
    + getName() : String
    + getPopulation() : long
    + getArea() : double
    + getPopulationDensity() : double
}

class CountryStatistics {
    + readFromFile(filename : String) : void
    + getLargestAreaCountry() : Country
    + getLargestPopulationCountry() : Country
    + getLargestDensityCountry() : Country
}

CountryStatistics  o--  Country

@enduml
